# Generated by Django 4.1.4 on 2023-07-05 07:41

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Careers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobTitle", models.CharField(max_length=200)),
                ("jobCategory", models.CharField(max_length=200)),
                ("requisitionNumber", models.CharField(max_length=200)),
                ("schedule", models.CharField(max_length=200)),
                ("discription", models.CharField(max_length=1000)),
                ("date", models.DateTimeField()),
                ("detailDiscription", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=500)),
                (
                    "categoryLink",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("discription", models.TextField()),
                (
                    "metaTitle",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "metaDescription",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images/logo/")),
                (
                    "link",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="contactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=80)),
                ("phoneNo", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("companyName", models.CharField(max_length=100)),
                ("query", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("isSuscribed", models.BooleanField(default=False)),
                ("isInquiry", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile1",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isMobile1", models.BooleanField(default=False)),
                (
                    "mobile2",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isMobile2", models.BooleanField(default=False)),
                (
                    "mobile3",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isMobile3", models.BooleanField(default=False)),
                (
                    "email1",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isEmail1", models.BooleanField(default=False)),
                (
                    "email2",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isEmail2", models.BooleanField(default=False)),
                (
                    "email3",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isEmail3", models.BooleanField(default=False)),
                (
                    "addressLabel",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "aboutUsLabel",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "addressText",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "aboutUsText",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "contactLabel",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReachUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading1", models.CharField(max_length=200)),
                ("heading2", models.CharField(max_length=200)),
                ("lableOfName", models.CharField(max_length=200)),
                ("textFiledName", models.CharField(max_length=200)),
                ("lableOfQuery", models.CharField(max_length=200)),
                ("textFiledOfQuery", models.CharField(max_length=200)),
                ("lableOfEmail", models.CharField(max_length=200)),
                ("textFiledOfEmail", models.CharField(max_length=200)),
                ("lableOfAddress", models.CharField(max_length=200)),
                ("textFiledOfAddress", models.CharField(max_length=200)),
                ("lableOfCountry", models.CharField(max_length=200)),
                ("textFiledOfCountry", models.CharField(max_length=200)),
                ("lableOfSubscription", models.CharField(max_length=200)),
                ("lableOfCompany", models.CharField(max_length=200)),
                ("textFiledOfCompany", models.CharField(max_length=200)),
                ("textOfSubmit", models.CharField(max_length=200)),
                (
                    "labelOfPhone",
                    models.CharField(default="Mobile no.", max_length=200),
                ),
                (
                    "textFiledOfPhone",
                    models.CharField(default="+91 82008xxxxx", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "videoId",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="images/poster/"
                    ),
                ),
                ("isUploaded", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subCategoryName", models.CharField(max_length=500)),
                ("discription", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.CharField(max_length=500)),
                ("isMHE", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=500)),
                (
                    "modelNo",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("isOnHome", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("images", models.ImageField(upload_to="images/")),
                ("isUploaded", models.BooleanField(default=False)),
                (
                    "productLink",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "ytLink",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "productPdf",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="pdf/"
                    ),
                ),
                (
                    "metaTitle",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "metaDescription",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to="api.ip"
                    ),
                ),
                (
                    "star",
                    models.ManyToManyField(
                        blank=True, related_name="Star", to="api.star"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=80)),
                ("mobileNo", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=500)),
                ("resume", models.FileField(upload_to="resumes/")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.careers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now=True)),
                ("isUploaded", models.BooleanField(default=False)),
                (
                    "blogLink",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "author",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("views", models.IntegerField(default=0)),
                (
                    "stars",
                    models.JSONField(
                        blank=True, default=api.models.Blog.default_json, null=True
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=api.models.Blog.default_json, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="images/blog/"
                    ),
                ),
                ("isActive", models.BooleanField(default=False)),
                ("isApproved", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "metaDescription",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="blog_likes", to="api.ip"
                    ),
                ),
            ],
        ),
    ]
