# Generated by Django 4.1.4 on 2023-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="subCategoryLink",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
