# Generated by Django 4.1.4 on 2023-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isUploaded",
            field=models.BooleanField(default=False),
        ),
    ]
