# Generated by Django 4.1.4 on 2023-08-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_subcategory_subcategorylink"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subCategory",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subcategory",
            ),
        ),
    ]
