# Generated by Django 4.1.4 on 2023-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_isuploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="modelNo",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
