# Generated by Django 4.1.4 on 2023-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_product_modelno"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="categoryLink",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
