# Generated by Django 4.1.11 on 2023-09-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image4',
            field=models.ImageField(null=True, upload_to='mimages/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image5',
            field=models.ImageField(null=True, upload_to='mimages/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image6',
            field=models.ImageField(null=True, upload_to='mimages/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image7',
            field=models.ImageField(null=True, upload_to='mimages/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(null=True, upload_to='mimages/'),
        ),
    ]
