# Generated by Django 4.1.4 on 2023-03-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_footer_ourclients"),
    ]

    operations = [
        migrations.RenameModel(old_name="OurClients", new_name="Clients",),
    ]
