# Generated by Django 4.2.5 on 2024-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productimage_image1_alter_productimage_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('country', models.CharField(default='', max_length=20)),
                ('company', models.CharField(default='', max_length=20)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
