# Generated by Django 4.1.4 on 2023-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_ourclients_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="image",
            field=models.ImageField(upload_to="images/logo/"),
        ),
    ]
