# Generated by Django 5.0.3 on 2024-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_inquiryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='adForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('country', models.CharField(default='', max_length=20)),
                ('company', models.CharField(default='', max_length=20)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='InquiryForm',
        ),
    ]
