# Generated by Django 4.1.4 on 2023-03-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_clients_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "videoLink",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("poster", models.ImageField(upload_to="images/poster/")),
            ],
        ),
    ]
