# Generated by Django 4.1.4 on 2023-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_youtubevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="isUploaded",
            field=models.BooleanField(default=False),
        ),
    ]
