# Generated by Django 4.1.4 on 2023-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_youtubevideo_isuploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideo",
            name="poster",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images/poster/"
            ),
        ),
    ]
