# Generated by Django 4.1.4 on 2023-03-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_youtubevideo_poster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtubevideo", old_name="videoLink", new_name="videoId",
        ),
    ]
