# Generated by Django 5.2 on 2025-04-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
