# Generated by Django 4.1.4 on 2023-03-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote", name="isMHE", field=models.BooleanField(default=False),
        ),
    ]
