# Generated by Django 4.1.4 on 2023-03-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_quote_ismhe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
    ]
