# Generated by Django 4.1.4 on 2023-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_quote_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=80)),
                ("phoneNo", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("companyName", models.CharField(max_length=100)),
                ("query", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("isSuscribed", models.BooleanField(default=False)),
            ],
        ),
    ]
