# Generated by Django 4.1.4 on 2023-03-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_product_productlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="likes", to="api.ip"),
        ),
    ]
