# Generated by Django 4.1.4 on 2023-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_ip_product_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ip", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
